2019/10/26 10:41:50 [error] 12237#12237: *1 open() "/home/fabiano/Documentos/projetos/www/html/api-rest-python-servicenet/venv/lib/python3.6/site-packages/rest_framework_swagger/staticrest_framework_swagger/bundles/vendors.bundle.js" failed (2: No such file or directory), client: 127.0.0.1, server: api-servicenet-desafio.com, request: "GET /static/rest_framework_swagger/bundles/vendors.bundle.js HTTP/1.1", host: "api-servicenet-desafio.com:8006", referrer: "http://api-servicenet-desafio.com:8006/api/docs/"
2019/10/26 10:41:50 [error] 12237#12237: *1 open() "/home/fabiano/Documentos/projetos/www/html/api-rest-python-servicenet/venv/lib/python3.6/site-packages/rest_framework_swagger/staticrest_framework_swagger/bundles/app.bundle.js" failed (2: No such file or directory), client: 127.0.0.1, server: api-servicenet-desafio.com, request: "GET /static/rest_framework_swagger/bundles/app.bundle.js HTTP/1.1", host: "api-servicenet-desafio.com:8006", referrer: "http://api-servicenet-desafio.com:8006/api/docs/"
2019/10/26 10:41:50 [error] 12237#12237: *1 open() "/home/fabiano/Documentos/projetos/www/html/api-rest-python-servicenet/venv/lib/python3.6/site-packages/rest_framework_swagger/staticrest_framework_swagger/bundles/app.bundle.css" failed (2: No such file or directory), client: 127.0.0.1, server: api-servicenet-desafio.com, request: "GET /static/rest_framework_swagger/bundles/app.bundle.css HTTP/1.1", host: "api-servicenet-desafio.com:8006", referrer: "http://api-servicenet-desafio.com:8006/api/docs/"
2019/10/26 10:41:50 [error] 12237#12237: *3 open() "/home/fabiano/Documentos/projetos/www/html/api-rest-python-servicenet/venv/lib/python3.6/site-packages/rest_framework_swagger/staticrest_framework_swagger/bundles/vendors.bundle.css" failed (2: No such file or directory), client: 127.0.0.1, server: api-servicenet-desafio.com, request: "GET /static/rest_framework_swagger/bundles/vendors.bundle.css HTTP/1.1", host: "api-servicenet-desafio.com:8006", referrer: "http://api-servicenet-desafio.com:8006/api/docs/"
2019/10/26 10:41:50 [error] 12237#12237: *1 open() "/home/fabiano/Documentos/projetos/www/html/api-rest-python-servicenet/venv/lib/python3.6/site-packages/rest_framework_swagger/staticrest_framework_swagger/logo_small.png" failed (2: No such file or directory), client: 127.0.0.1, server: api-servicenet-desafio.com, request: "GET /static/rest_framework_swagger/logo_small.png HTTP/1.1", host: "api-servicenet-desafio.com:8006", referrer: "http://api-servicenet-desafio.com:8006/api/docs/"
2019/10/26 10:41:50 [error] 12237#12237: *3 open() "/home/fabiano/Documentos/projetos/www/html/api-rest-python-servicenet/venv/lib/python3.6/site-packages/rest_framework_swagger/staticrest_framework_swagger/bundles/vendors.bundle.js" failed (2: No such file or directory), client: 127.0.0.1, server: api-servicenet-desafio.com, request: "GET /static/rest_framework_swagger/bundles/vendors.bundle.js HTTP/1.1", host: "api-servicenet-desafio.com:8006", referrer: "http://api-servicenet-desafio.com:8006/api/docs/"
2019/10/26 10:41:50 [error] 12237#12237: *3 open() "/home/fabiano/Documentos/projetos/www/html/api-rest-python-servicenet/venv/lib/python3.6/site-packages/rest_framework_swagger/staticrest_framework_swagger/bundles/app.bundle.js" failed (2: No such file or directory), client: 127.0.0.1, server: api-servicenet-desafio.com, request: "GET /static/rest_framework_swagger/bundles/app.bundle.js HTTP/1.1", host: "api-servicenet-desafio.com:8006", referrer: "http://api-servicenet-desafio.com:8006/api/docs/"
2019/10/26 10:41:52 [error] 12237#12237: *5 open() "/home/fabiano/Documentos/projetos/www/html/api-rest-python-servicenet/venv/lib/python3.6/site-packages/rest_framework_swagger/staticrest_framework_swagger/bundles/vendors.bundle.css" failed (2: No such file or directory), client: 127.0.0.1, server: api-servicenet-desafio.com, request: "GET /static/rest_framework_swagger/bundles/vendors.bundle.css HTTP/1.1", host: "api-servicenet-desafio.com:8006", referrer: "http://api-servicenet-desafio.com:8006/api/docs/"
2019/10/26 10:41:52 [error] 12237#12237: *7 open() "/home/fabiano/Documentos/projetos/www/html/api-rest-python-servicenet/venv/lib/python3.6/site-packages/rest_framework_swagger/staticrest_framework_swagger/bundles/app.bundle.css" failed (2: No such file or directory), client: 127.0.0.1, server: api-servicenet-desafio.com, request: "GET /static/rest_framework_swagger/bundles/app.bundle.css HTTP/1.1", host: "api-servicenet-desafio.com:8006", referrer: "http://api-servicenet-desafio.com:8006/api/docs/"
2019/10/26 10:41:52 [error] 12237#12237: *8 open() "/home/fabiano/Documentos/projetos/www/html/api-rest-python-servicenet/venv/lib/python3.6/site-packages/rest_framework_swagger/staticrest_framework_swagger/bundles/vendors.bundle.js" failed (2: No such file or directory), client: 127.0.0.1, server: api-servicenet-desafio.com, request: "GET /static/rest_framework_swagger/bundles/vendors.bundle.js HTTP/1.1", host: "api-servicenet-desafio.com:8006", referrer: "http://api-servicenet-desafio.com:8006/api/docs/"
2019/10/26 10:41:52 [error] 12237#12237: *9 open() "/home/fabiano/Documentos/projetos/www/html/api-rest-python-servicenet/venv/lib/python3.6/site-packages/rest_framework_swagger/staticrest_framework_swagger/bundles/app.bundle.js" failed (2: No such file or directory), client: 127.0.0.1, server: api-servicenet-desafio.com, request: "GET /static/rest_framework_swagger/bundles/app.bundle.js HTTP/1.1", host: "api-servicenet-desafio.com:8006", referrer: "http://api-servicenet-desafio.com:8006/api/docs/"
2019/10/26 10:41:52 [error] 12237#12237: *7 open() "/home/fabiano/Documentos/projetos/www/html/api-rest-python-servicenet/venv/lib/python3.6/site-packages/rest_framework_swagger/staticrest_framework_swagger/logo_small.png" failed (2: No such file or directory), client: 127.0.0.1, server: api-servicenet-desafio.com, request: "GET /static/rest_framework_swagger/logo_small.png HTTP/1.1", host: "api-servicenet-desafio.com:8006", referrer: "http://api-servicenet-desafio.com:8006/api/docs/"
2019/10/26 10:41:53 [error] 12237#12237: *8 open() "/home/fabiano/Documentos/projetos/www/html/api-rest-python-servicenet/venv/lib/python3.6/site-packages/rest_framework_swagger/staticrest_framework_swagger/bundles/vendors.bundle.js" failed (2: No such file or directory), client: 127.0.0.1, server: api-servicenet-desafio.com, request: "GET /static/rest_framework_swagger/bundles/vendors.bundle.js HTTP/1.1", host: "api-servicenet-desafio.com:8006", referrer: "http://api-servicenet-desafio.com:8006/api/docs/"
2019/10/26 10:41:53 [error] 12237#12237: *9 open() "/home/fabiano/Documentos/projetos/www/html/api-rest-python-servicenet/venv/lib/python3.6/site-packages/rest_framework_swagger/staticrest_framework_swagger/bundles/app.bundle.js" failed (2: No such file or directory), client: 127.0.0.1, server: api-servicenet-desafio.com, request: "GET /static/rest_framework_swagger/bundles/app.bundle.js HTTP/1.1", host: "api-servicenet-desafio.com:8006", referrer: "http://api-servicenet-desafio.com:8006/api/docs/"
2019/10/26 10:43:15 [error] 12396#12396: *6 open() "/home/fabiano/Documentos/projetos/www/html/api-rest-python-servicenet/venv/lib/python3.6/site-packages/rest_framework_swagger/staticrest_framework_swagger/bundles/vendors.bundle.css" failed (2: No such file or directory), client: 127.0.0.1, server: api-servicenet-desafio.com, request: "GET /static/rest_framework_swagger/bundles/vendors.bundle.css HTTP/1.1", host: "api-servicenet-desafio.com:8006", referrer: "http://api-servicenet-desafio.com:8006/api/docs/"
2019/10/26 10:43:15 [error] 12396#12396: *6 open() "/home/fabiano/Documentos/projetos/www/html/api-rest-python-servicenet/venv/lib/python3.6/site-packages/rest_framework_swagger/staticrest_framework_swagger/bundles/app.bundle.css" failed (2: No such file or directory), client: 127.0.0.1, server: api-servicenet-desafio.com, request: "GET /static/rest_framework_swagger/bundles/app.bundle.css HTTP/1.1", host: "api-servicenet-desafio.com:8006", referrer: "http://api-servicenet-desafio.com:8006/api/docs/"
2019/10/26 10:43:15 [error] 12396#12396: *6 open() "/home/fabiano/Documentos/projetos/www/html/api-rest-python-servicenet/venv/lib/python3.6/site-packages/rest_framework_swagger/staticrest_framework_swagger/bundles/vendors.bundle.js" failed (2: No such file or directory), client: 127.0.0.1, server: api-servicenet-desafio.com, request: "GET /static/rest_framework_swagger/bundles/vendors.bundle.js HTTP/1.1", host: "api-servicenet-desafio.com:8006", referrer: "http://api-servicenet-desafio.com:8006/api/docs/"
2019/10/26 10:43:15 [error] 12396#12396: *6 open() "/home/fabiano/Documentos/projetos/www/html/api-rest-python-servicenet/venv/lib/python3.6/site-packages/rest_framework_swagger/staticrest_framework_swagger/bundles/app.bundle.js" failed (2: No such file or directory), client: 127.0.0.1, server: api-servicenet-desafio.com, request: "GET /static/rest_framework_swagger/bundles/app.bundle.js HTTP/1.1", host: "api-servicenet-desafio.com:8006", referrer: "http://api-servicenet-desafio.com:8006/api/docs/"
2019/10/26 10:43:16 [error] 12396#12396: *6 open() "/home/fabiano/Documentos/projetos/www/html/api-rest-python-servicenet/venv/lib/python3.6/site-packages/rest_framework_swagger/staticrest_framework_swagger/logo_small.png" failed (2: No such file or directory), client: 127.0.0.1, server: api-servicenet-desafio.com, request: "GET /static/rest_framework_swagger/logo_small.png HTTP/1.1", host: "api-servicenet-desafio.com:8006", referrer: "http://api-servicenet-desafio.com:8006/api/docs/"
2019/10/26 10:43:16 [error] 12396#12396: *6 open() "/home/fabiano/Documentos/projetos/www/html/api-rest-python-servicenet/venv/lib/python3.6/site-packages/rest_framework_swagger/staticrest_framework_swagger/bundles/vendors.bundle.js" failed (2: No such file or directory), client: 127.0.0.1, server: api-servicenet-desafio.com, request: "GET /static/rest_framework_swagger/bundles/vendors.bundle.js HTTP/1.1", host: "api-servicenet-desafio.com:8006", referrer: "http://api-servicenet-desafio.com:8006/api/docs/"
2019/10/26 10:43:16 [error] 12396#12396: *6 open() "/home/fabiano/Documentos/projetos/www/html/api-rest-python-servicenet/venv/lib/python3.6/site-packages/rest_framework_swagger/staticrest_framework_swagger/bundles/app.bundle.js" failed (2: No such file or directory), client: 127.0.0.1, server: api-servicenet-desafio.com, request: "GET /static/rest_framework_swagger/bundles/app.bundle.js HTTP/1.1", host: "api-servicenet-desafio.com:8006", referrer: "http://api-servicenet-desafio.com:8006/api/docs/"
2019/10/26 11:12:24 [error] 12396#12396: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: api-servicenet-desafio.com, request: "GET /api/docs/ HTTP/1.1", upstream: "http://127.0.0.1:8007/api/docs/", host: "api-servicenet-desafio.com:8006"
2019/10/26 11:12:25 [error] 12396#12396: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: api-servicenet-desafio.com, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:8007/favicon.ico", host: "api-servicenet-desafio.com:8006"
2019/10/26 11:12:32 [error] 12396#12396: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: api-servicenet-desafio.com, request: "GET /api/cliente/1 HTTP/1.1", upstream: "http://127.0.0.1:8007/api/cliente/1", host: "api-servicenet-desafio.com:8006"
2019/10/26 11:43:25 [error] 12396#12396: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: api-servicenet-desafio.com, request: "GET /api/cliente/1 HTTP/1.1", upstream: "http://127.0.0.1:8007/api/cliente/1", host: "api-servicenet-desafio.com:8006"
2019/10/26 12:32:41 [error] 19662#19662: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: api-servicenet-desafio.com, request: "GET /api/cliente/1 HTTP/1.1", upstream: "http://127.0.0.1:8007/api/cliente/1", host: "api-servicenet-desafio.com:8006"
2019/10/26 12:32:45 [error] 19662#19662: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: api-servicenet-desafio.com, request: "GET /api/cliente/1 HTTP/1.1", upstream: "http://127.0.0.1:8007/api/cliente/1", host: "api-servicenet-desafio.com:8006"
2019/10/26 12:33:54 [error] 19662#19662: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: api-servicenet-desafio.com, request: "GET /api/cliente/1 HTTP/1.1", upstream: "http://127.0.0.1:8007/api/cliente/1", host: "api-servicenet-desafio.com:8006"
2019/10/26 12:33:55 [error] 19662#19662: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: api-servicenet-desafio.com, request: "GET /api/cliente/1 HTTP/1.1", upstream: "http://127.0.0.1:8007/api/cliente/1", host: "api-servicenet-desafio.com:8006"
2019/10/26 12:44:20 [error] 19662#19662: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: api-servicenet-desafio.com, request: "GET /api/cliente/1 HTTP/1.1", upstream: "http://127.0.0.1:8007/api/cliente/1", host: "api-servicenet-desafio.com:8006"
